### ISSUE TITLE
Some questions for this

### ISSUE THREAD

**Issue by antinomypa** [LvWind/NotRunningInBg#1]
I have tried this and it worked well. 

At first, I just clicked the start button in app but nothing happened. So I try to snooze the notification for 15 min and after 15 min the notification didn't appear. So is this the right way to use it?

If I want background app notification appear again, what should I do? Just uninstall it?

**Comment by LvWind** [comment]
Thank you for your feedback.
Yeah, and i will add some guide to tell user how to operate.
Actually, I have not find a way to un-snooze the notify yet, uninstall didn't work.And im working on it.

**Comment by antinomypa** [comment]
Today, I restarted my phone for some reason, and...the background notification appeared again. I don't know what happened. I think it may be helpful to your work.

**Comment by LvWind** [comment]
Thanks, i will confirm it.
