### ISSUE TITLE
App is not work as intended

### ISSUE THREAD

**Issue by Jack-Works** [LvWind/NotRunningInBg#6]
Device:  Pixel, Android 8.0
Version: 0.3
- [x] Permission granted
- [x] Switch to Enable in main activity
- [x] Snooze the notification manually

The app does not snooze the notification as intended to.

Guessing reason:
Maybe cause by notification change, the number of  app running in the background becomes 2 from 1, and cause some kind of ID changes, then this app can not snooze it in the next duration. (Not verified, just a hypothesis)

Maybe the app hasn't snooze any notification programmatically.

**Comment by LvWind** [comment]
hmm, i can not reproduce, What's your system language locale? And what are these 2 apps?

**Comment by Jack-Works** [comment]
System language: en-UK
Apps: Shadowsocks and Keepass

**Comment by LvWind** [comment]
![1504575722560](https://user-images.githubusercontent.com/280190/30041666-814714c0-921e-11e7-82a0-6ad9c8811044.jpg)
There's an \n\t\t line break in the string of en-rGB.
I will check all language files and upload a new version, Thank you for your feedback.

**Comment by Jack-Works** [comment]
Hmm, why not just match "running in the background" in title?

**Comment by Jack-Works** [comment]
Oh I forgot other languages ( lol

**Comment by LvWind** [comment]
There are two type of the notificationTitle string, singular and plural. And they are all different in different languages. But the notificationText string won't change when your background apps from 1 to 2.

**Comment by Jack-Works** [comment]
Still not resolved when more than 1 app is running in the background
Notification of 1 app:
Notification text = Tap for details on battery and data usage

Notification of more than 1 app:
Notification text = Keepass, Shadowsocks are running in the background

**Comment by LvWind** [comment]
You can try v0.5
I found a better way to filter notifications

**Comment by Jack-Works** [comment]
I think I shall wait for a 15 mins.

By the way, since it is using channel ID to identify this type of notification, can we just snooze it when it was created or sent? Therefore it can snooze it automatically. Is there any technical limits?

**Comment by LvWind** [comment]
I have snoozed it when the notification created already. You need to snooze it manually once, because I can not cancel a system notification and recreate it programmatically.

You can disconnect shadowsocks and reconnect to trigger the new notification post event without waiting for 15 mins.

**Comment by Jack-Works** [comment]
Alright, by this way, I verified that app is still not working for me, even in 1 app scenario. Do I have any way to collect log or something?

**Comment by LvWind** [comment]
hmm, try reinstall and reboot your phone.
I turned off log in release build. If reboot doesn't work, I'll build a debug version for you tomorrow.

**Comment by Jack-Works** [comment]
Great, a reboot make it works.
Thanks for your work

**Comment by Jack-Works** [comment]
Not working again, have no idea about why this happening
